#define CHUNK_AXIS1_SIZE 16
#define CHUNK_AXIS2_SIZE CHUNK_AXIS1_SIZE * CHUNK_AXIS1_SIZE
#define CHUNK_AXIS3_SIZE CHUNK_AXIS1_SIZE * CHUNK_AXIS1_SIZE * CHUNK_AXIS1_SIZE
#define CHUNK_MEM_SIZE CHUNK_AXIS3_SIZE * sizeof(uint32_t)