#include <numbers>

#define CHUNK_AXIS1_SIZE 64
#define CHUNK_AXIS2_SIZE CHUNK_AXIS1_SIZE * CHUNK_AXIS1_SIZE
#define CHUNK_AXIS3_SIZE CHUNK_AXIS1_SIZE * CHUNK_AXIS1_SIZE * CHUNK_AXIS1_SIZE
#define CHUNK_MEM_SIZE CHUNK_AXIS3_SIZE * sizeof(uint32_t)
#define RENDER_DISTANCE 16
#define NUM_CHUNKS_IN_SCENE (RENDER_DISTANCE * 2 + 1) * (RENDER_DISTANCE * 2 + 1)